site_name: Giuseppe Bassi
site_description: Appunti, Olimpiadi e materiale — Bocconi BAI
# site_url: https://giuseppebassi.github.io/giuseppe-site/   # (opzionale: metti qui l’URL finale)

nav:
  - Home: index.md
  - Notes / Materiali: notes.md

theme:
  name: material
  language: it
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - header.autohide
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    # Il tuo CSS definisce i colori → usiamo "custom" per entrambi gli schemi
    - scheme: default
      primary: custom
      accent: custom
    - scheme: slate
      primary: custom
      accent: custom
  icon:
    logo: material/account-circle
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@bassigiuseppe
      name: YouTube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/giuseppe-bassi/
      name: LinkedIn
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/bassii.giuseppe/
      name: Instagram
    - icon: material/email
      link: mailto:giuseppe.bassi2@studbocconi.it
      name: Email

repo_url: https://github.com/GiuseppeBassi
repo_name: GiuseppeBassi
edit_uri: ""

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - styles/overrides.css

plugins:
  - search
